[versions]
kotlin = "2.2.21"
kotlinxSerialization = "1.9.0"
kotlinxCoroutines = "1.8.1"
gdx = "1.13.5"
gdxAi = "1.8.2"
ktx = "1.13.1-rc1"
korlibs = "4.0.10"
kotest = "6.1.11"
junitPlatformLauncher = "1.8.2"
versionsPlugin = "0.51.0"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
gdx-ai = { module = "com.badlogicgames.gdx:gdx-ai", version.ref = "gdxAi" }
freetype-stripe = { module = "com.github.raeleus.stripe:freetype", version = "2.0.0" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.3" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.23" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine-jvm", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }